services:
  proxy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./ops/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - static_assets:/var/www/static:ro
    depends_on:
      - web

  web:
    build:
      context: ./backend
    env_file: .env
    depends_on:
      - db
      - cache
    volumes:
      - media:/app/media
      - static_assets:/app/staticfiles
    command: gunicorn config.wsgi:application -b 0.0.0.0:8000 -w 4

  worker:
    build:
      context: ./backend
    env_file: .env
    depends_on:
      - db
      - cache
    command: celery -A config worker -l INFO
    volumes:
      - media:/app/media

  beat:
    build:
      context: ./backend
    env_file: .env
    depends_on:
      - db
      - cache
    command: celery -A config beat -l INFO

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: auuction
      POSTGRES_USER: auuction
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backups:/backups

  cache:
    image: redis:7
    volumes:
      - redis_data:/data

volumes:
  caddy_data:
  caddy_config:
  static_assets:
  media:
  pg_data:
  redis_data:
