# Generated by Django 5.0.7 on 2025-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='at_church',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='location_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE auctions_profile "
                        "ADD COLUMN IF NOT EXISTS image varchar(100) NULL"
                    ),
                    reverse_sql=(
                        "ALTER TABLE auctions_profile "
                        "DROP COLUMN IF EXISTS image"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='profile',
                    name='image',
                    field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
                ),
            ],
        ),
    ]
