# Generated by Django 5.0.7 on 2025-08-26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_profile_image_db_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/', null=True, blank=True),
        ),
    ]
