# Generated by Django 5.0.7 on 2025-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='event_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='event_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
