# Generated by Django 5.0.7 on 2025-08-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_proxybid'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxybid',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
