name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Check for missing migrations
        working-directory: backend
        run: |
          python manage.py makemigrations --check --dry-run
      - name: Run migrations (SQLite)
        working-directory: backend
        run: |
          python manage.py migrate --noinput
      - name: Run tests
        working-directory: backend
        run: pytest -q
